name: Secret Scanner
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  
  scan:
    name: Scan
    steps:
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.90.8
